"""uptade article table

Revision ID: 0c6beb4146d5
Revises: fecb15b1fa96
Create Date: 2025-06-02 20:56:30.325623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c6beb4146d5"
down_revision: Union[str, None] = "fecb15b1fa96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("body", sa.Text(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "body")
    # ### end Alembic commands ###
