"""Create articles table

Revision ID: 34a1121e5c9d
Revises: 444f8c30d7d6
Create Date: 2025-06-02 19:23:20.584918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34a1121e5c9d"
down_revision: Union[str, None] = "444f8c30d7d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("body", sa.Text(), server_default="", nullable=False),
    )
    op.add_column(
        "articles", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(None, "articles", ["title"])
    op.create_foreign_key(None, "articles", "users", ["user_id"], ["id"])
    op.drop_column("articles", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("content", sa.VARCHAR(), nullable=False)
    )
    op.drop_constraint(None, "articles", type_="foreignkey")
    op.drop_constraint(None, "articles", type_="unique")
    op.drop_column("articles", "user_id")
    op.drop_column("articles", "body")
    # ### end Alembic commands ###
